name: fluttersdk_wind
description: "A Flutter plugin designed with a utility-first approach, inspired by Tailwind CSS, for building responsive, modular, and efficient UI components."
version: 1.0.0-alpha.1
homepage: https://wind.fluttersdk.com
repository: https://github.com/fluttersdk/wind
issue_tracker: https://github.com/fluttersdk/wind/issues

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0
  keyboard_actions: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
