name: fluttersdk_wind
description: "A Flutter plugin designed with a utility-first approach, inspired by Tailwind CSS, for building responsive, modular, and efficient UI components."
version: 0.0.4
homepage: https://wind.fluttersdk.com

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  platform_info: ^5.0.0
